# 📊 Análisis de Ventas - Proyecto de Data Analysis con Python

En este proyecto se realiza un análisis de datos de ventas simulados, aplicando limpieza, filtrado por fechas, generación de reportes con tablas dinámicas y exportación a una base de datos PostgreSQL.

Además, se aplican buenas prácticas de programación, como la modularización mediante funciones contenidas en un archivo externo (`funciones.py`).

## 🧭 Objetivos
- Importar y explorar desde una base de datos PostgreSQL. .
- Filtrar los datos según rangos de fecha definidos por el usuario.
- Crear reportes tipo tabla dinámica con Pandas.
- Exportar los resultados a una base de datos.

1. Para iniciar nuestro análisis, importamos las librerías necesarias. Pandas será nuestra herramienta principal para la manipulación de datos, mientras que SQLAlchemy y psycopg2 nos permitirán conectarnos y consultar nuestra base de datos de PostgreSQL. También importamos nuestras funciones personalizadas desde el archivo funciones.py para mantener el código modular.

In [168]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
from funciones import * # Asegúrate de que este archivo esté en la misma carpeta

2. Para mantener nuestro código limpio y modular, hemos definido la función leer_tabla en el archivo funciones.py. Esta función se encargará de leer cualquier tabla de nuestra base de datos y retornarla como un DataFrame de Pandas, simplificando la carga de datos a lo largo del proyecto.

In [169]:
def leer_tabla(tabla, engine):
    query = f"SELECT * FROM {tabla}"
    df = pd.read_sql(query, engine)
    return df

3. Para comenzar nuestro análisis, establecemos la conexión a la base de datos de PostgreSQL 'classicmodels'. Usaremos la librería SQLAlchemy para crear un motor de conexión (engine), que nos permitirá consultar las tablas de la base de datos.

In [ ]:
engine = create_engine("postgresql://postgres:postgres@localhost:5432/classicmodels")

4. Una vez establecida la conexión, procedemos a cargar todas las tablas relevantes de la base de datos en DataFrames de Pandas. Esto nos permitirá tener a nuestra disposición todos los datos de órdenes, clientes, productos y empleados para su posterior análisis y unión.

In [ ]:
# Leemos cada una de las tablas de la base de datos y las guardamos en DataFrames
orders_df = leer_tabla('orders', engine)
orderdetails_df = leer_tabla('orderdetails', engine)
customers_df = leer_tabla('customers', engine)
products_df = leer_tabla('products', engine)
employees_df = leer_tabla('employees', engine)

Revisamos cada una de las tablas

In [172]:
orders_df.head()

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,None,363
1,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128
2,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,None,181
3,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,None,121
4,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,None,141

In [173]:
orderdetails_df.head()

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10100    S18_1749               30     136.00                3
1        10100    S18_2248               50      55.09                2
2        10100    S18_4409               22      75.46                4
3        10100    S24_3969               49      35.29                1
4        10101    S18_2325               25     108.06                4

In [174]:
customers_df.head()

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.0
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.0
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300.0
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",None,Nantes,None,44000,France,1370.0,118200.0
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,None,Stavern,None,4110,Norway,1504.0,81700.0

In [175]:
products_df.head()

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00

In [176]:
employees_df.head()

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA)

5. Una vez que hemos cargado todas las tablas, las unimos en un solo DataFrame (df_base). Esto nos permitirá analizar toda la información de pedidos, clientes, productos y empleados de manera conjunta. Para garantizar la integridad de los datos, utilizamos el parámetro validate en cada unión, asegurando que las relaciones entre las tablas son correctas.

In [ ]:
# Unificamos las tablas en un solo DataFrame usando merge
df_base=orders_df.\
          merge(orderdetails_df, on='orderNumber', validate='one_to_many').\
          merge(customers_df,on='customerNumber', validate='many_to_one').\
          merge(products_df, on='productCode' , validate= 'many_to_one').\
          merge(employees_df, left_on='salesRepEmployeeNumber' , right_on='employeeNumber', validate= 'many_to_one')

# Verificamos la forma (dimensiones) del nuevo DataFrame
print(f"La forma del DataFrame final es: {df_base.shape}")

# Mostramos las primeras filas para confirmar que todo se unió correctamente
print("\nPrimeras 5 filas del DataFrame unificado:")
print(df_base.head())

La forma del DataFrame final es: (2996, 39)

Primeras 5 filas del DataFrame unificado:
   orderNumber   orderDate requiredDate shippedDate   status  \
0        10100  2003-01-06   2003-01-13  2003-01-10  Shipped
1        10100  2003-01-06   2003-01-13  2003-01-10  Shipped
2        10100  2003-01-06   2003-01-13  2003-01-10  Shipped
3        10100  2003-01-06   2003-01-13  2003-01-10  Shipped
4        10101  2003-01-09   2003-01-18  2003-01-11  Shipped

                 comments  customerNumber productCode  quantityOrdered  \
0                    None             363    S18_1749               30
1                    None             363    S18_2248               50
2                    None             363    S18_4409               22
3                    None             363    S24_3969               49
4  Check on availability.             128    S18_2325               25

   priceEach  ...  buyPrice    MSRP employeeNumber   lastName firstName  \
0     136.00  ...     86.70  170.00           1216  Patterson     Steve
1      55.09  ...     33.30   60.54           1216  Patterson     Steve
2      75.46  ...     43.26   92.03           1216  Patterson     Steve
3      35.29  ...     21.75   41.03           1216  Patterson     Steve
4     108.06  ...     58.48  127.13           1504      Jones     Barry

  extension                            email officeCode reportsTo   jobTitle
0     x4334  spatterson@classicmodelcars.com          2    1143.0  Sales Rep
1     x4334  spatterson@classicmodelcars.com          2    1143.0  Sales Rep
2     x4334  spatterson@classicmodelcars.com          2    1143.0  Sales Rep
3     x4334  spatterson@classicmodelcars.com          2    1143.0  Sales Rep
4      x102      bjones@classicmodelcars.com          7    1102.0  Sales Rep

[5 rows x 39 columns]

6. Una vez unificadas las tablas, revisamos las primeras filas de df_base para asegurarnos de que la estructura sea la esperada y que los datos se hayan combinado correctamente.

In [179]:
df_base

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,productCode,quantityOrdered,priceEach,...,buyPrice,MSRP,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,None,363,S18_1749,30,136.00,...,86.70,170.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep
1,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,None,363,S18_2248,50,55.09,...,33.30,60.54,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep
2,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,None,363,S18_4409,22,75.46,...,43.26,92.03,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep
3,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,None,363,S24_3969,49,35.29,...,21.75,41.03,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep
4,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S18_2325,25,108.06,...,58.48,127.13,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,10425,2005-05-31,2005-06-07,None,In Process,None,119,S24_2300,49,127.79,...,61.34,127.79,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep
2992,10425,2005-05-31,2005-06-07,None,In Process,None,119,S24_2840,31,31.82,...,15.91,35.36,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep
2993,10425,2005-05-31,2005-06-07,None,In Process,None,119,S32_1268,41,83.79,...,53.93,96.31,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep
2994,10425,2005-05-31,2005-06-07,None,In Process,None,119,S32_2509,11,50.32,...,25.98,54.11,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep
2995,10425,2005-05-31,2005-06-07,None,In Process,None,119,S50_1392,18,94.92,...,68.29,115.75,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep

7. Antes de calcular las nuevas columnas, revisamos los tipos de datos de las columnas clave (quantityOrdered, priceEach, buyPrice). Esto asegura que las operaciones matemáticas se realizarán correctamente.

In [180]:
df_base.quantityOrdered

0       30
1       50
2       22
3       49
4       25
        ..
2991    49
2992    31
2993    41
2994    11
2995    18
Name: quantityOrdered, Length: 2996, dtype: int64

In [181]:
df_base.priceEach

0       136.00
1        55.09
2        75.46
3        35.29
4       108.06
         ...
2991    127.79
2992     31.82
2993     83.79
2994     50.32
2995     94.92
Name: priceEach, Length: 2996, dtype: float64

In [182]:
df_base.buyPrice

0       86.70
1       33.30
2       43.26
3       21.75
4       58.48
        ...
2991    61.34
2992    15.91
2993    53.93
2994    25.98
2995    68.29
Name: buyPrice, Length: 2996, dtype: float64

In [183]:
df_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2996 entries, 0 to 2995
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   orderNumber             2996 non-null   int64
 1   orderDate               2996 non-null   object
 2   requiredDate            2996 non-null   object
 3   shippedDate             2855 non-null   object
 4   status                  2996 non-null   object
 5   comments                758 non-null    object
 6   customerNumber          2996 non-null   int64
 7   productCode             2996 non-null   object
 8   quantityOrdered         2996 non-null   int64
 9   priceEach               2996 non-null   float64
 10  orderLineNumber         2996 non-null   int64
 11  customerName            2996 non-null   object
 12  contactLastName         2996 non-null   object
 13  contactFirstName        2996 non-null   object
 14  phone                   2996 non-null   object
 15  addressLine1            2996 non-null   object
 16  addressLine2            592 non-null    object
 17  city                    2996 non-null   object
 18  state                   1337 non-null   object
 19  postalCode              2823 non-null   object
 20  country                 2996 non-null   object
 21  salesRepEmployeeNumber  2996 non-null   float64
 22  creditLimit             2996 non-null   float64
 23  productName             2996 non-null   object
 24  productLine             2996 non-null   object
 25  productScale            2996 non-null   object
 26  productVendor           2996 non-null   object
 27  productDescription      2996 non-null   object
 28  quantityInStock         2996 non-null   int64
 29  buyPrice                2996 non-null   float64
 30  MSRP                    2996 non-null   float64
 31  employeeNumber          2996 non-null   int64
 32  lastName                2996 non-null   object
 33  firstName               2996 non-null   object
 34  extension               2996 non-null   object
 35  email                   2996 non-null   object
 36  officeCode              2996 non-null   object
 37  reportsTo               2996 non-null   float64
 38  jobTitle                2996 non-null   object
dtypes: float64(6), int64(6), object(27)
memory usage: 913.0+ KB

## Creación de nuevas metricas

8. Una vez unificadas las tablas, procedemos a enriquecer nuestro DataFrame con nuevas columnas que nos permitirán realizar un análisis de rentabilidad. Calculamos el total de ventas, el costo de los productos y la ganancia por cada transacción.

In [184]:
# Realizamos los calculos pedidos
df_base['venta']=df_base['quantityOrdered']*df_base['priceEach']
df_base['costo']=df_base['quantityOrdered']*df_base['buyPrice']
df_base['ganancia']=df_base['venta']-df_base['costo']

# Verificamos que las nuevas columnas se hayan creado correctamente
print("Columnas agregadas exitosamente. Las primeras 5 filas se ven así:")
df_base[['venta', 'costo', 'ganancia']].head()

Columnas agregadas exitosamente. Las primeras 5 filas se ven así:

     venta    costo  ganancia
0  4080.00  2601.00   1479.00
1  2754.50  1665.00   1089.50
2  1660.12   951.72    708.40
3  1729.21  1065.75    663.46
4  2701.50  1462.00   1239.50

9. ¿Cuál fue el total de ventas por cada línea de productos?

Ahora, para responder a la pregunta de negocio, calculamos el total de ventas por cada línea de productos. Esto nos permitirá identificar cuáles son las categorías más rentables y cuáles necesitan atención. Utilizaremos una tabla dinámica para resumir los datos.

In [185]:
total_ventas=pd.pivot_table(data = df_base,
                         index='productLine',
                         values=['venta'],
                         margins= True,
                         aggfunc='sum').round(2) # creacion de la tabla pivote

Una vez generada la tabla dinámica, revisamos el reporte final para validar los totales de ventas por cada línea de productos y asegurarnos de que la suma total sea la esperada.

In [186]:
total_ventas

                       venta
productLine
Classic Cars      3853922.49
Motorcycles       1121426.12
Planes             954637.54
Ships              663998.34
Trains             188532.92
Trucks and Buses  1024113.57
Vintage Cars      1797559.63
All               9604190.61

Para entender mejor la base de clientes, contamos la cantidad de clientes únicos que realizaron una compra. Esto nos da una métrica clave sobre el alcance de nuestras ventas.

10.  ¿Cuántos clientes únicos hicieron compras y cuántos no han realizado ninguna?

Para responder a la pregunta de negocio, contamos el número de clientes únicos que realizaron compras. Esta es una métrica clave para entender la dimensión de nuestra base de clientes.

In [187]:
# Para saber cuantos clientes hiceron compras contamos la columna 'customerNumber' del Dataframe 
# df_base con el metodo nunique
clientes_que_hicieron_compras = df_base['customerNumber'].nunique()

# Imprimimos el resultado de forma clara
print("Número de clientes distintos que hicieron compras es de :",clientes_que_hicieron_compras)

Número de clientes distintos que hicieron compras es de : 98

Para identificar oportunidades de crecimiento, buscamos clientes que aún no han realizado ninguna compra. Comparando la lista completa de clientes con la de aquellos que ya han comprado, podemos saber cuántos son y enfocar estrategias de marketing en ellos

In [188]:
# 1. Contamos el total de clientes en la tabla de clientes
total_clientes = customers_df['customerNumber'].nunique()

# 2. Contamos los clientes que sí realizaron compras (esta variable ya la calculaste)
# clientes_que_hicieron_compras = df_base['customerNumber'].nunique()

# 3. Calculamos la diferencia
clientes_sin_compras = total_clientes - clientes_que_hicieron_compras

# Imprimimos los resultados de forma clara
print(f"El número total de clientes en la base de datos es: {total_clientes}")
print(f"El número de clientes que hicieron compras es: {clientes_que_hicieron_compras}")
print(f"El número de clientes que no han hecho compras es de: {clientes_sin_compras}")

El número total de clientes en la base de datos es: 122
El número de clientes que hicieron compras es: 98
El número de clientes que no han hecho compras es de: 24

11. ¿Cuáles fueron los 10 clientes con mayores ventas brutas en dinero durante el año 2005?

 Para responder a la pregunta de negocio, primero filtramos los datos por el año 2005. Para ello, convertimos la columna orderDate a un tipo de dato datetime, lo que nos permitirá extraer el año y realizar el filtro de forma correcta.

Para responder a la pregunta, primero revisamos los tipos de datos de las columnas relevantes. La columna orderDate debe ser de tipo datetime para poder filtrar por año.

In [189]:

#Para hacer un filtro por años revisamos que exista una columna de fechas y que esta tenga el formato adecuado 
df_base.info()

#encontramos la columna orderNumber , pero esta como tipo de dato object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2996 entries, 0 to 2995
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   orderNumber             2996 non-null   int64
 1   orderDate               2996 non-null   object
 2   requiredDate            2996 non-null   object
 3   shippedDate             2855 non-null   object
 4   status                  2996 non-null   object
 5   comments                758 non-null    object
 6   customerNumber          2996 non-null   int64
 7   productCode             2996 non-null   object
 8   quantityOrdered         2996 non-null   int64
 9   priceEach               2996 non-null   float64
 10  orderLineNumber         2996 non-null   int64
 11  customerName            2996 non-null   object
 12  contactLastName         2996 non-null   object
 13  contactFirstName        2996 non-null   object
 14  phone                   2996 non-null   object
 15  addressLine1            2996 non-null   object
 16  addressLine2            592 non-null    object
 17  city                    2996 non-null   object
 18  state                   1337 non-null   object
 19  postalCode              2823 non-null   object
 20  country                 2996 non-null   object
 21  salesRepEmployeeNumber  2996 non-null   float64
 22  creditLimit             2996 non-null   float64
 23  productName             2996 non-null   object
 24  productLine             2996 non-null   object
 25  productScale            2996 non-null   object
 26  productVendor           2996 non-null   object
 27  productDescription      2996 non-null   object
 28  quantityInStock         2996 non-null   int64
 29  buyPrice                2996 non-null   float64
 30  MSRP                    2996 non-null   float64
 31  employeeNumber          2996 non-null   int64
 32  lastName                2996 non-null   object
 33  firstName               2996 non-null   object
 34  extension               2996 non-null   object
 35  email                   2996 non-null   object
 36  officeCode              2996 non-null   object
 37  reportsTo               2996 non-null   float64
 38  jobTitle                2996 non-null   object
 39  venta                   2996 non-null   float64
 40  costo                   2996 non-null   float64
 41  ganancia                2996 non-null   float64
dtypes: float64(9), int64(6), object(27)
memory usage: 983.2+ KB

Convertimos la columna orderDate de tipo 'object' a tipo 'datetime', lo cual nos permitirá extraer el año y realizar un filtro de manera eficiente.

In [190]:
#transformamos el tipo de dato a date
df_base['orderDate'] = pd.to_datetime(df_base['orderDate'])

In [191]:
#confirmamos el tipo de dato 'datetime'
print(df_base['orderDate'].dtypes)

datetime64[ns]

Una vez realizada la conversión, verificamos la columna orderDate para confirmar que su tipo de dato ahora es datetime64[ns].

In [192]:
df_base.info() #revisamos las columnas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2996 entries, 0 to 2995
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   orderNumber             2996 non-null   int64
 1   orderDate               2996 non-null   datetime64[ns]
 2   requiredDate            2996 non-null   object
 3   shippedDate             2855 non-null   object
 4   status                  2996 non-null   object
 5   comments                758 non-null    object
 6   customerNumber          2996 non-null   int64
 7   productCode             2996 non-null   object
 8   quantityOrdered         2996 non-null   int64
 9   priceEach               2996 non-null   float64
 10  orderLineNumber         2996 non-null   int64
 11  customerName            2996 non-null   object
 12  contactLastName         2996 non-null   object
 13  contactFirstName        2996 non-null   object
 14  phone                   2996 non-null   object
 15  addressLine1            2996 non-null   object
 16  addressLine2            592 non-null    object
 17  city                    2996 non-null   object
 18  state                   1337 non-null   object
 19  postalCode              2823 non-null   object
 20  country                 2996 non-null   object
 21  salesRepEmployeeNumber  2996 non-null   float64
 22  creditLimit             2996 non-null   float64
 23  productName             2996 non-null   object
 24  productLine             2996 non-null   object
 25  productScale            2996 non-null   object
 26  productVendor           2996 non-null   object
 27  productDescription      2996 non-null   object
 28  quantityInStock         2996 non-null   int64
 29  buyPrice                2996 non-null   float64
 30  MSRP                    2996 non-null   float64
 31  employeeNumber          2996 non-null   int64
 32  lastName                2996 non-null   object
 33  firstName               2996 non-null   object
 34  extension               2996 non-null   object
 35  email                   2996 non-null   object
 36  officeCode              2996 non-null   object
 37  reportsTo               2996 non-null   float64
 38  jobTitle                2996 non-null   object
 39  venta                   2996 non-null   float64
 40  costo                   2996 non-null   float64
 41  ganancia                2996 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(6), object(26)
memory usage: 983.2+ KB

Para responder a la pregunta de negocio, primero filtramos el DataFrame para incluir únicamente las ventas correspondientes al año 2005. Esto nos permitirá centrarnos en el período de análisis

In [194]:
# Creamos un DataFrame que contenga las ventas de año 2005 con la funcion creada 'filtrar_por_tabla' que esta en archivo funciones.py
from funciones import filtrar_por_fecha
ventas_2005 = filtrar_por_fecha(df_base, 'orderDate', '2005-01-01', '2005-12-31')

# Verificamos las primeras filas para confirmar que el filtro funcionó
print("Primeras 20 filas del DataFrame 'ventas_2005':")
ventas_2005.head(20)  #muestra la tabla creada

Primeras 20 filas del DataFrame 'ventas_2005':

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,productCode,quantityOrdered,priceEach,...,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,venta,costo,ganancia
2473,10362,2005-01-05,2005-01-16,2005-01-10,Shipped,None,161,S10_4698,22,182.04,...,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,4004.88,2002.44,2002.44
2474,10362,2005-01-05,2005-01-16,2005-01-10,Shipped,None,161,S12_2823,22,131.04,...,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,2882.88,1457.94,1424.94
2475,10362,2005-01-05,2005-01-16,2005-01-10,Shipped,None,161,S18_2625,23,53.91,...,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,1239.93,557.29,682.64
2476,10362,2005-01-05,2005-01-16,2005-01-10,Shipped,None,161,S24_1578,50,91.29,...,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,4564.50,3043.00,1521.50
2477,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S12_1099,33,180.95,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,5971.35,3146.22,2825.13
2478,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S12_3380,34,106.87,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,3633.58,2555.44,1078.14
2479,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S12_3990,34,68.63,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,2333.42,1085.28,1248.14
2480,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S12_4675,46,103.64,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,4767.44,2701.58,2065.86
2481,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S18_1889,22,61.60,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1355.20,1185.80,169.40
2482,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S18_3278,46,69.15,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,3180.90,2256.30,924.60
2483,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S18_3482,24,124.94,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,2998.56,1763.76,1234.80
2484,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S18_3782,32,52.22,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1671.04,1054.40,616.64
2485,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S18_4721,28,123.50,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,3458.00,1958.04,1499.96
2486,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S24_2000,21,70.08,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1471.68,783.72,687.96
2487,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S24_2360,43,56.10,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,2412.30,2025.30,387.00
2488,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S24_3371,21,52.05,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1093.05,810.18,282.87
2489,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S24_3856,31,113.75,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,3526.25,3047.30,478.95
2490,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S24_4620,43,75.99,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,3267.57,1390.19,1877.38
2491,10363,2005-01-06,2005-01-12,2005-01-10,Shipped,None,334,S32_1374,50,92.90,...,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,4645.00,3346.00,1299.00
2492,10364,2005-01-06,2005-01-17,2005-01-09,Shipped,None,350,S32_2206,48,38.22,...,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep,1834.56,1158.72,675.84

Utilizamos la función generar_reporte para crear un resumen de las ventas, costos y ganancias de cada cliente en el año 2005. Esta función agrupa los datos de forma automática, lo que nos facilita el análisis y nos prepara para identificar a los clientes principales.

In [196]:
# Creamos un DataFrame con la suma de las columnas 'venta', 'costo' y 'ganancia' agrupados por 'customerName' con la funcion 'generar_reporte'
from funciones import generar_reporte
clientes_ventas = generar_reporte(ventas_2005,
                                  filas= 'customerName',
                                  valores=['venta', 'costo', 'ganancia'],
                                  medida='sum')
                                
# Verificamos la tabla creada y mostramos los 10 clientes con mayores ventas
print("Reporte de ventas por cliente en 2005:")
clientes_ventas.sort_values(by='venta', ascending=False).head(10)

Reporte de ventas por cliente en 2005:

                                  venta      costo   ganancia
customerName
Euro+ Shopping Channel        290018.52  169989.97  120028.55
Mini Gifts Distributors Ltd.  192481.73  115084.72   77397.01
La Rochelle Gifts              91147.11   55527.04   35620.07
The Sharp Gifts Warehouse      83984.89   50843.02   33141.87
Down Under Souveniers, Inc     75020.13   46389.52   28630.61
Anna's Decorations, Ltd        56932.30   35414.90   21517.40
Salzburg Collectables          52420.07   33536.26   18883.81
Gifts4AllAges.com              50806.85   33221.25   17585.60
Corporate Gift Ideas Co.       46781.66   28561.31   18220.35
Oulu Toy Supplies, Inc.        46770.52   27493.61   19276.91

Para responder a la pregunta de negocio, ordenamos el reporte de clientes por sus ventas totales en orden descendente y seleccionamos los 10 primeros. El resultado es un DataFrame con los clientes más importantes del año 2005.

In [197]:
# Ordenamos el DataFrame por ventas de forma descendente y seleccionamos los 10 primeros
top_10_clientes = clientes_ventas.sort_values(by='venta', ascending=False).head(10)

# Reiniciamos el índice para una presentación más limpia
top_10_clientes = top_10_clientes.reset_index(drop=True)


# Mostramos los resultados finales
print("Los 10 clientes con mayores ventas brutas en 2005 son:")
top_10_clientes

Los 10 clientes con mayores ventas brutas en 2005 son:

       venta      costo   ganancia
0  290018.52  169989.97  120028.55
1  192481.73  115084.72   77397.01
2   91147.11   55527.04   35620.07
3   83984.89   50843.02   33141.87
4   75020.13   46389.52   28630.61
5   56932.30   35414.90   21517.40
6   52420.07   33536.26   18883.81
7   50806.85   33221.25   17585.60
8   46781.66   28561.31   18220.35
9   46770.52   27493.61   19276.91

Una vez que hemos identificado a los 10 clientes con mayores ventas brutas, guardamos el resultado en una nueva tabla en PostgreSQL. Esto nos permite almacenar los hallazgos de forma permanente para futuras consultas o reportes.

In [198]:

from funciones import escribir_en_base_de_datos
escribir_en_base_de_datos(top_10_clientes, 'top_10_clientes_2005', engine)

# Mensaje de confirmación
print("DataFrame 'top_10_clientes_2005' guardado exitosamente en PostgreSQL.")

Datos escritos correctamente en la tabla 'top_10_clientes_2005'.
DataFrame 'top_10_clientes_2005' guardado exitosamente en PostgreSQL.

12. ¿Cuáles fueron los 10 artículos más vendidos durante el año 2005, considerando la cantidad neta?

Para identificar los productos más exitosos del año 2005, calculamos la cantidad total vendida de cada artículo. Esto nos permitirá crear un ranking de los 10 productos más populares, una métrica clave para la gestión de inventario y estrategia de marketing."

In [200]:

from funciones import generar_reporte
productos_mas_vendidos = generar_reporte(ventas_2005,
                                  filas= 'productName',
                                  valores=['quantityOrdered','venta', 'costo', 'ganancia'],
                                  medida='sum')


# Mostramos las primeras 5 filas para verificar el resultado
print("Reporte de productos con sus métricas clave:")
productos_mas_vendidos.head()

Reporte de productos con sus métricas clave:

,quantityOrdered,venta,costo,ganancia
productName,,,,
18th Century Vintage Horse Carriage,140,13110.81,8503.60,4607.21
18th century schooner,157,16561.87,12927.38,3634.49
1900s Vintage Bi-Plane,150,8756.75,5137.50,3619.25
1900s Vintage Tri-Plane,238,15940.74,8622.74,7318.00
1903 Ford Model A,126,16233.55,8605.80,7627.75

Para identificar los productos más exitosos, ordenamos nuestro reporte de forma descendente por la cantidad vendida. Seleccionamos los 10 primeros resultados para crear un ranking de los artículos más populares en el 2005.

In [201]:
# Ordenamos el DataFrame por la cantidad de artículos vendidos y seleccionamos los 10 primeros
top_10_productos_2005 = productos_mas_vendidos.sort_values(by='quantityOrdered', ascending=False).head(10)

# Reiniciamos el índice para una presentación más limpia
top_10_productos_2005 = top_10_productos_2005.reset_index(drop=True)

# Mostramos los resultados finales
print("Los 10 productos más vendidos en 2005 son:")
top_10_productos_2005

Los 10 productos más vendidos en 2005 son:

   quantityOrdered     venta     costo  ganancia
0              347  52978.28  27031.30  25946.98
1              272  29567.27  15974.56  13592.71
2              271  28747.69  16493.06  12254.63
3              257  22469.91  17198.44   5271.47
4              255  31432.14  25066.50   6365.64
5              242  16049.47   9031.44   7018.03
6              238  15940.74   8622.74   7318.00
7              231  30434.09  15308.37  15125.72
8              230  26139.34  15867.70  10271.64
9              226  20918.96  14595.08   6323.88

Una vez que hemos identificado a los 10 productos más vendidos, guardamos el resultado en una nueva tabla en PostgreSQL llamada 'top_10_productos_2005'. Esto nos permite almacenar los hallazgos de forma permanente para futuras consultas o reportes.

In [202]:
# Tu código para escribir en la base de datos (corregido)
from funciones import escribir_en_base_de_datos
escribir_en_base_de_datos(top_10_productos_2005, 'top_10_productos_2005', engine)

# Mensaje de confirmación
print("DataFrame 'top_10_productos_2005' guardado exitosamente en PostgreSQL.")

Datos escritos correctamente en la tabla 'top_10_productos_2005'.
DataFrame 'top_10_productos_2005' guardado exitosamente en PostgreSQL.